
skillMetadata:
  sections:
    - name: MPD-Radio
      fields:
        - name: radio
          type: text
          label: Standardradio (IP 1)
          value: localhost
          placeholder: localhost
        - name: port
          type: number
          label: Port
          value: 6600
          placeholder: 6600
